#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Aliases

# Editor aliases
alias edit='subl ~/.zprezto'
alias sub='subl .'

# GIT ALIASES
alias go='git checkout'
alias st='git status'
alias gp='git pull --rebase'
alias gph='git push heroku master'

# Tail the log
alias tlog='tail -f log/development.log'

# Jekyll
alias jekyll='bundle exec jekyll'
alias jnew='thor jekyll:new'

alias s='spring'
