#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Aliases
alias audiofix="sudo kill `ps -ax | grep 'coreaudiod' | grep 'sbin' |awk '{print $1}'`"


# Editor aliases
alias edit='subl ~/.zprezto'
alias sub='subl .'

# GIT ALIASES
alias gs='git-up'
alias go='git checkout'
alias st='git status -sb'
alias gp='git pull --rebase'
alias gph='git push heroku master'

# Rails
alias tlog='tail -f log/development.log'
alias s='spring'
alias sc='spring rails console'
alias sr='spring rspec'

alias jnew='thor jekyll:new'
